blank_issues_enabled: true
contact_links:
  - name: FinTech API
    url: https://github.com/Clueless-Community/fintech-api/blob/main/.github/ISSUE_TEMPLATE/issue_template.md
    about: Create an issue regarding a bug or feature requirest here.
