name: Linting with black

on:
  push:
      paths-ignore:
        - 'main.p**'
  pull_request:
      paths-ignore:
        - 'main.p**'
      
jobs:

  black-linting:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: psf/black@stable
